// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: greeting.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcService {
  public static partial class HelloService
  {
    static readonly string __ServiceName = "todo.HelloService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.Request> __Marshaller_todo_Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.Response> __Marshaller_todo_Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.Response.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.Request, global::GrpcService.Response> __Method_UnaryService = new grpc::Method<global::GrpcService.Request, global::GrpcService.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UnaryService",
        __Marshaller_todo_Request,
        __Marshaller_todo_Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.Request, global::GrpcService.Response> __Method_ClientStreamingService = new grpc::Method<global::GrpcService.Request, global::GrpcService.Response>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "ClientStreamingService",
        __Marshaller_todo_Request,
        __Marshaller_todo_Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.Request, global::GrpcService.Response> __Method_ServerStreamingService = new grpc::Method<global::GrpcService.Request, global::GrpcService.Response>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ServerStreamingService",
        __Marshaller_todo_Request,
        __Marshaller_todo_Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.Request, global::GrpcService.Response> __Method_BidirectionalStreamingService = new grpc::Method<global::GrpcService.Request, global::GrpcService.Response>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "BidirectionalStreamingService",
        __Marshaller_todo_Request,
        __Marshaller_todo_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcService.GreetingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloService</summary>
    [grpc::BindServiceMethod(typeof(HelloService), "BindService")]
    public abstract partial class HelloServiceBase
    {
      /// <summary>
      /// Unary call
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcService.Response> UnaryService(global::GrpcService.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Client streaming
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcService.Response> ClientStreamingService(grpc::IAsyncStreamReader<global::GrpcService.Request> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Server streaming
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task ServerStreamingService(global::GrpcService.Request request, grpc::IServerStreamWriter<global::GrpcService.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Bidirectional streaming
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task BidirectionalStreamingService(grpc::IAsyncStreamReader<global::GrpcService.Request> requestStream, grpc::IServerStreamWriter<global::GrpcService.Response> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(HelloServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UnaryService, serviceImpl.UnaryService)
          .AddMethod(__Method_ClientStreamingService, serviceImpl.ClientStreamingService)
          .AddMethod(__Method_ServerStreamingService, serviceImpl.ServerStreamingService)
          .AddMethod(__Method_BidirectionalStreamingService, serviceImpl.BidirectionalStreamingService).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UnaryService, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.Request, global::GrpcService.Response>(serviceImpl.UnaryService));
      serviceBinder.AddMethod(__Method_ClientStreamingService, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::GrpcService.Request, global::GrpcService.Response>(serviceImpl.ClientStreamingService));
      serviceBinder.AddMethod(__Method_ServerStreamingService, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::GrpcService.Request, global::GrpcService.Response>(serviceImpl.ServerStreamingService));
      serviceBinder.AddMethod(__Method_BidirectionalStreamingService, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::GrpcService.Request, global::GrpcService.Response>(serviceImpl.BidirectionalStreamingService));
    }

  }
}
#endregion
